### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/fm-overlays#15]
- [x] Overlay post building
- [x] Conditions Targeting System
- [x] Priority System

**Comment by gfargo** [comment]
Currently the following are being tested for in PR #17:
- Overlay Post Building
- Conditional Targeting System

**Comment by gfargo** [comment]
PR #17 now contains the `test-overlay-display-priority` class with a basic priority test.  This was added in d1a7f88.

The current test creates two basic overlays, **overlay a** has a `menu_order` of 1 while **overlay b** has a `menu_order` of 5.  The test ensures that **overlay b** is displaying on the page.

**Comment by jakewrfoster** [comment]
🐴
