### ISSUE TITLE
Add field for user to control overlay display frequency

### ISSUE THREAD

**Issue by gfargo** [alleyinteractive/fm-overlays#18]
Add an additional meta fields to the Overlay screen to allow the user to override the cookie expiration time being set in Javascript.  

Create a new `data-frequency` attribute attached to the overlay DOM Node and have the JS dynamically set the expiration time based on the meta field attached to the overlay.

**Comment by jakewrfoster** [comment]
Working on: #23

**Comment by jakewrfoster** [comment]
#23 Closes this issue and uses a `data-expiration`.

![image](https://user-images.githubusercontent.com/1018205/38392933-c66b702e-38ee-11e8-8793-bad4cb9a76cc.png)
